### ISSUE TITLE
repeated

### ISSUE THREAD

**Issue by pengpeng** [pomelonode/pomelo-protobuf#1]
1. 如果在 json文件中添加repeated string域：
   网络传输会失败
2. 在json文件中添加:repeated int32域,传输正常，但客户端解析的json串有冗余信息
   服务器端数据为：poker : [1,2,3,4]
   以repeated int32 传输后，在客户端解析为
   "poker" : [ {"poker":1},{"poker":2},{"poker":3},{"poker":4}]

**Comment by fantasyni** [comment]
[论坛已解决](http://nodejs.netease.com/topic/51dec60fb6c6203329062649)

**Comment by demon0925** [comment]
问题已修正，具体反馈见论坛中同样的问题：http://nodejs.netease.com/topic/51dec60fb6c6203329062649
